title: Meppies Blog
description: This is Meppies blog, where I share knowledge that I see in my work.

url: https://meppie.eu
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about    
    - title: Articles
      url: /articles

social:
    github: Meppies
    twitter: crasymeppie
    email: meppies@meppies.nl
    linkedin: jeroenmeppelink
    youtube: TheMeppies
    bluesky: meppe.link

google_analytics: 

disqus:
    shortname: Meppie
